capture: 0
Traceback (most recent call last):
  File "/KWH/datalogger/datetime/datetime.py", line 3, in <module>
    execfile("/KWH/datalogger/config/pyvars.py")
  File "/KWH/datalogger/config/pyvars.py", line 25, in <module>
    with open('/KWH/datalogger/config/DOMAIN', 'r') as config:
IOError: [Errno 2] No such file or directory: '/KWH/datalogger/config/DOMAIN'
datetime: 0
temp: 0
cat: /KWH/datalogger/config/DOMAIN: No such file or directory
cat: /KWH/datalogger/config/PORT: No such file or directory
signal: 0
Traceback (most recent call last):
  File "/KWH/datalogger/modbus/queryAll.py", line 7, in <module>
    execfile("/KWH/datalogger/config/pyvars.py")
  File "/KWH/datalogger/config/pyvars.py", line 25, in <module>
    with open('/KWH/datalogger/config/DOMAIN', 'r') as config:
IOError: [Errno 2] No such file or directory: '/KWH/datalogger/config/DOMAIN'
modbus: 1
Traceback (most recent call last):
  File "/KWH/datalogger/transceive/tcp/tstring.py", line 5, in <module>
    execfile(DPATH + "/config/pyvars.py")
  File "/KWH/datalogger/config/pyvars.py", line 25, in <module>
    with open('/KWH/datalogger/config/DOMAIN', 'r') as config:
IOError: [Errno 2] No such file or directory: '/KWH/datalogger/config/DOMAIN'
tstring: 0
cat: /KWH/datalogger/config/DOMAIN: No such file or directory
cat: /KWH/datalogger/config/PORT: No such file or directory
tcpSend: 0
Traceback (most recent call last):
  File "/KWH/datalogger/transceive/sms/smsParse.py", line 8, in <module>
    execfile("/KWH/datalogger/config/pyvars.py")
  File "/KWH/datalogger/config/pyvars.py", line 25, in <module>
    with open('/KWH/datalogger/config/DOMAIN', 'r') as config:
IOError: [Errno 2] No such file or directory: '/KWH/datalogger/config/DOMAIN'
smsParse: 0
