Traceback (most recent call last):
  File "/KWH/datalogger/transceive/sms/smsParse.py", line 8, in <module>
    execfile("/KWH/datalogger/config/pyvars.py")
  File "/KWH/datalogger/config/pyvars.py", line 25, in <module>
    with open('/KWH/datalogger/config/DOMAIN', 'r') as config:
IOError: [Errno 2] No such file or directory: '/KWH/datalogger/config/DOMAIN'
Connected to MySQL datalogger database
1
Connection to MySQL datalogger database is closed
Connected to MySQL datalogger database
1
Connection to MySQL datalogger database is closed
Connected to MySQL datalogger database
1
Connection to MySQL datalogger database is closed
Connected to MySQL datalogger database
1
Connection to MySQL datalogger database is closed
Connected to MySQL datalogger database
1
Connection to MySQL datalogger database is closed
